"$schema" = "https://starship.rs/config-schema.json"

palette = "gruvbox_dark"
add_newline = false
format = """
[](color_orange)\
${os}\
${username}\
[](bg:color_yellow fg:color_orange)\
${directory}\
[](fg:color_yellow bg:color_aqua)\
${git_branch}\
${git_status}\
${git_state}\
[](fg:color_aqua bg:color_blue)\
${c}\
${cpp}\
${rust}\
${golang}\
${nodejs}\
${php}\
${java}\
${kotlin}\
${haskell}\
${python}\
[](fg:color_blue bg:color_bg3)\
${docker_context}\
${conda}\
${pixi}\
[ ](fg:color_bg3)\
${fill}\
[](color_bg3)\
${status}\
[](fg:color_bg3 bg:color_bg1)\
${cmd_duration}\
[](fg:color_bg1 bg:color_bg3)\
${time}\
[ ](fg:color_bg3)\
${line_break}\
${character}\
"""

[cmd_duration]
disabled = false
min_time = 0
format = "[[  ${duration} ](fg:color_fg0 bg:color_bg1)](${style})"

[time]
disabled = false
time_format = "%r"
style = "bg:color_bg3"
format = "[[  ${time}](fg:color_fg0 bg:color_bg3)](${style})"

[status]
symbol = "✘"
success_symbol = "✔"
format = "[[${symbol}](${style})](${style})"
success_style = "bold bg:color_bg3 fg:color_aqua"
failure_style = "bold bg:color_bg3 fg:color_red"
disabled = false

[palettes.gruvbox_dark]
color_fg0 = "#fbf1c7"
color_bg1 = "#3c3836"
color_bg3 = "#665c54"
color_blue = "#458588"
color_aqua = "#689d6a"
color_green = "#98971a"
color_success = "#008000"
color_orange = "#d65d0e"
color_purple = "#b16286"
color_red = "#cc241d"
color_yellow = "#d79921"

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"
format = "[[ ${symbol}(${os} ) ](fg:color_fg0 bg:color_orange)](${style})"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
disabled = true
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = "[ ${user} ](${style})"

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ ${path} ](${style})"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = "[[ ${symbol} ${branch} ](fg:color_fg0 bg:color_aqua)](${style})"

[git_status]
disabled = false
conflicted = "️${count}"
ahead = "️${count}"
behind = "${count}"
diverged = "${ahead_count} ${behind_count}"
untracked = "${count}"
modified = "󰙏${count}"
staged = "${count}"
deleted = "${count}"
renamed = "${count}"
stashed = ""
style = "bg:color_aqua"
format = "[[(${all_status}${ahead_behind} )](fg:color_fg0 bg:color_aqua)](${style})"

[git_state]
disabled = false
format = "[[\\(${state}( ${progress_current}/${progress_total})\\)](bold fg:color_yellow bg:color_aqua)](${style})"
style = "bg:color_aqua"

[nodejs]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[c]
symbol = " "
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[cpp]
symbol = " "
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[rust]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[golang]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[php]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[java]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[kotlin]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[haskell]
symbol = ""
style = "bg:color_blue"
format = "[[ ${symbol}( ${version}) ](fg:color_fg0 bg:color_blue)](${style})"

[python]
symbol = ""
style = "bg:color_blue"
detect_extensions = []
detect_files = []
format = "[[( ${symbol} ${version}( \\(${virtualenv}\\)) )](fg:color_fg0 bg:color_blue)](${style})"

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = "[[ ${symbol}( ${context}) ](fg:#83a598 bg:color_bg3)](${style})"

[conda]
style = "bg:color_bg3"
format = "[[ ${symbol}( ${environment}) ](fg:#83a598 bg:color_bg3)](${style})"

[pixi]
style = "bg:color_bg3"
format = "[[ ${symbol}( ${version})( ${environment}) ](fg:color_fg0 bg:color_bg3)](${style})"

[line_break]
disabled = false

[fill]
symbol = " "

[character]
disabled = false
success_symbol = "[❯](bold fg:color_green)"
error_symbol = "[❯](bold fg:color_red)"
vimcmd_symbol = "[](bold fg:color_green)"
vimcmd_replace_one_symbol = "[](bold fg:color_purple)"
vimcmd_replace_symbol = "[](bold fg:color_purple)"
vimcmd_visual_symbol = "[](bold fg:color_yellow)"
