##########################################################
######################### TAPS ###########################
##########################################################

##########################################################
####################### UTILITIES ########################
##########################################################

brew "asdf"
brew "bat"
brew "ca-certificates"
brew "checkov"
brew "coreutils"
brew "curl"
brew "direnv"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "glances"
brew "gnupg"
brew "go"
brew "go-task/tap/go-task"
brew "grep"
brew "hashicorp/tap/terraform"
brew "helm"
brew "htop"
brew "hugo"
brew "jc"
brew "jq"
brew "k9s"
brew "libomp"
brew "make"
brew "nano"
brew "neovim"
brew "node"
brew "nvm"
brew "openjdk"
brew "pipx"
brew "ripgrep"
brew "rich-cli"
brew "sops"
brew "starship"
brew "terraform-docs"
brew "terragrunt"
brew "thefuck"
brew "tree"
brew "wget"
brew "yq"
brew "zoxide"

##########################################################
######################### CASKS ##########################
##########################################################

cask "1password", greedy: true
cask "amazon-q", greedy: true
cask "caffeine", greedy: true
cask "cyberduck", greedy: true
cask "docker-desktop", greedy: true
cask "elgato-stream-deck", greedy: true
cask "ghostty", greedy: true
cask "github", greedy: true
cask "google-chrome", greedy: true
cask "hammerspoon", greedy: true
cask "iterm2", greedy: true
cask "jetbrains-toolbox", greedy: true
cask "lens", greedy: true
cask "logi-options+", greedy: true
cask "maccy", greedy: true
cask "ollama-app", greedy: true
cask "slack", greedy: true
cask "sourcetree", greedy: true
cask "spotify", greedy: true
cask "visual-studio-code", greedy: true
cask "vivaldi", greedy: true
cask "vlc", greedy: true
cask "zoom", greedy: true

##########################################################
######################### FONTS ##########################
##########################################################

cask "font-fontawesome", greedy: true
cask "font-meslo-lg-nerd-font", greedy: true

##########################################################
#################### PYTHON + PYENV ######################
##########################################################

brew "openssl"
brew "readline"
brew "sqlite3"
brew "tcl-tk"
brew "xz"
brew "zlib"
