##########################################################
################## COMPOSITE BREWFILE ####################
##########################################################

BREWFILES_DIR = File.join(__dir__, "brewfiles")
def include_brewfile(name)
  path = File.join(BREWFILES_DIR, "#{name}")
  instance_eval(File.read(path))
end

include_brewfile "taps.Brewfile"
include_brewfile "formulae.Brewfile"
include_brewfile "ai.Brewfile"
include_brewfile "casks.Brewfile"
include_brewfile "fonts.Brewfile"
