#!/usr/bin/env bash

set -e

if command -v dnf &>/dev/null; then
    PACKAGE_MANAGER="dnf"
elif command -v yum &>/dev/null; then
    PACKAGE_MANAGER="yum"
else
    echo "dnf/yum not detected, exiting ❌"
    exit 1
fi

##########################################################
########################## CORE ##########################
##########################################################

${PACKAGE_MANAGER} install --allowerasing -y \
    git \
    curl \
    wget \
    gettext \
    cmake \
    unzip \
    ninja-build

##########################################################
####################### UTILITIES ########################
##########################################################

${PACKAGE_MANAGER} install -y \
    gh \
    git-lfs \
    grep \
    htop \
    jq \
    make \
    nano \
    tree

# direnv
# fzf
# pipx
# ripgrep

##########################################################
#################### PYTHON + PYENV ######################
##########################################################

${PACKAGE_MANAGER} install -y \
    gcc \
    make \
    patch \
    zlib-devel \
    bzip2 \
    bzip2-devel \
    readline-devel \
    sqlite \
    sqlite-devel \
    openssl-devel \
    tk-devel \
    libffi-devel \
    xz-devel
